channels:
  - conda-forge
  - hdsr-mid
dependencies:
  - python>=3.8,<=3.12
  - hdsr-pygithub>1.14 # on conda channel hdsr-mid
  - requests
  - geopandas
  - pandas
  - isort  # dev tool: only required for auto-format code
  - black  # dev tool: only required for auto-format code
  - pytest  # dev tool: only required for running old_tests
  - pytest-cov  # dev tool: only required for running old_tests coverage
