channels:
  - conda-forge
  - hdsr-mid
dependencies:
  - python>=3.7
  - requests
  - pandas
  - geopandas
  - pathlib
  - typing
  - hdsr-pygithub  # on conda channel hdsr-mid
  - validators  # to validate pi_settings' base_url and test_url
  - isort  # dev tool: only required for auto-format code
  - black  # dev tool: only required for auto-format code
  - pytest  # dev tool: only required for running old_tests
  - pytest-cov  # dev tool: only required for running old_tests coverage
