channels:
  - conda-forge
  - hdsr-mid
dependencies:
  - python>=3.7,<=3.11
  - hdsr-pygithub
  - requests
  - pandas
  - geopandas
  - validators  # to validate pi_settings' base_url and test_url
  - rasterstats
  - rasterio
  - xarray
  - rioxarray
  - pytest  # dev tool: only required for running old_tests
  - pytest-cov  # dev tool: only required for running old_tests coverage
  - isort  # dev tool: only required for auto-format code
  - black  # dev tool: only required for auto-format code
