channels:
  - conda-forge
  # - defaults
dependencies:
  - python=3.7
  - aiohttp
  - nest-asyncio
  - requests
  - pandas
  - geopandas
  - pathlib
  - typing
  - isort  # only required for auto-format code
  - black  # only required for auto-format code
  - pytest  # only required for running tests
  - pytest-cov  # only required for running tests coverage
  #  - hdsr-wis-config-reader  # on conda channel hdsr-mid
  #  - hdsr-pygithub  # on conda channel hdsr-mid
